#!/bin/bash

#SBATCH --job-name=test      ## Name of the job.
#SBATCH -A elread_lab_rareevents     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1    ## number of cores the job needs
#SBATCH --error=error_%A_%a.txt ## error log file; %A is job id, %a is array task id
#SBATCH --output=out_%A_%a.txt  ## output filename
#SBATCH --time=7-00:00:00          ## time limit for each array task
#SBATCH --mail-type=BEGIN,END,ARRAY_TASKS
#SBATCH --mail-user=kbogue1@uci.edu
#SBATCH --array=1-100           ## number of array tasks 

# echo job info on log:
echo "Job $A $a started on:   " `hostname -s`
echo "Job $A $a started on:   " `date `
pwd
cd ..
pwd
## ./metropolis.out parameters.txt outputfilename verbose(should be 0) NFil N iSite(should be -1) baseSepDist(0 for single, 16.667000 for dimer or double) Force(always 0 for these models) dimerForce(10 for dimer)

 ./metropolis.out parameters.txt test_output_$i.txt 0 1 $i -1 0 0 0 &>/dev/null

 echo "metropolis finished running"

 rm metropolis.out parameters.txt ISEED

 echo "deleted metropolis.out parameters.txt ISEED"


# echo job info on joblog:
echo "Job $A $a ended on:   " `hostname -s`
echo "Job $A $a ended on:   " `date `
echo " "