#!/bin/bash

#SBATCH --job-name=double_0.207_2026.05.05_15.48.47      ## Name of the job.
#SBATCH -A elread_lab_rareevents     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=1    ## number of cores the job needs
#SBATCH --error=run.double.N%a_2026.05.05_15.48.47/error_%A_%a.txt ## error log file; %A is job id, %a is array task id. 
#SBATCH --output=run.double.N%a_2026.05.05_15.48.47/out_%A_%a.txt  ## output filename. 
#SBATCH --time=7-00:00:00          ## time limit for each array task
#SBATCH --mail-type=BEGIN,END,ARRAY_TASKS
#SBATCH --mail-user=kbogue1@uci.edu
#SBATCH --array=25-25           ## number of array tasks. 

# echo job info on log:
echo "Job $A $a started on:   " `hostname -s`
echo "Job $A $a started on:   " `date `
pwd
cd ..
pwd
## ./metropolis.out parameters.txt outputfilename verbose(should be 0) NFil N iSite(should be -1) baseSepDist(0 for single, 16.667000 for dimer or double) Force(always 0 for these models) dimerForce(10 for dimer)

 ./metropolis.out parameters.txt output_double.N${SLURM_ARRAY_TASK_ID}.iSite.BSD0.207.force.kdimer0.txt 1 2 $SLURM_ARRAY_TASK_ID -1 0.207 0 0

 echo "metropolis finished running"

 rm metropolis.out parameters.txt ISEED

 echo "deleted metropolis.out parameters.txt ISEED"


# echo job info on joblog:
echo "Job $A $a ended on:   " `hostname -s`
echo "Job $A $a ended on:   " `date `
echo " "
